#cloud-config
package_update: true

write_files:
  - path: /etc/grafana/grafana.ini
    content: |
      [server]
      protocol = http
      http_addr = 0.0.0.0
      http_port = 3000
      domain = ${public_ip}

runcmd:
  - apt-get install -y apt-transport-https software-properties-common wget gnupg
  - wget -q -O - https://packages.grafana.com/gpg.key | apt-key add -
  - add-apt-repository "deb https://packages.grafana.com/oss/deb stable main"
  - apt-get update
  - apt-get install -y grafana
  - systemctl enable grafana-server
  - systemctl restart grafana-server
