#cloud-config
package_update: true

# Install Grafana and its dependencies
runcmd:
  - apt-get install -y apt-transport-https software-properties-common wget gnupg
  - wget -q -O - https://packages.grafana.com/gpg.key | apt-key add -
  - add-apt-repository "deb https://packages.grafana.com/oss/deb stable main"
  - apt-get update
  - apt-get install -y grafana
  - systemctl enable grafana-server
  - systemctl start grafana-server
